default:
  host: "localhost"
  port: "5001"
  api_path: "api"
  api_version: "v2"
  simulator: "bluesky"
  bluesky_simulator: "bluesky"
  college_simulator: "college"

  # Bluebird API endpoints (to be removed in favour of OpenAPI)
  status_code_aircraft_id_not_found: 400
  status_code_no_aircraft_found: 400
  err_msg_aircraft_does_not_exist: "Aircraft .* does not exist"
  err_msg_aircraft_has_no_route: "Aircrafthasnoroute"
  endpoint_reset_simulation: "reset"
  endpoint_pause_simulation: "hold"
  endpoint_resume_simulation: "op"
  endpoint_set_simulation_rate_multiplier: "dtmult"
  endpoint_simulation_step: "step"
  endpoint_create_scenario: "scenario"
  endpoint_create_aircraft: "cre"
  endpoint_aircraft_position: "pos"
  endpoint_change_altitude: "alt"
  endpoint_change_heading: "hdg"
  endpoint_change_speed: "gspd"
  endpoint_add_waypoint: "addwpt"
  endpoint_direct_to_waypoint: "direct"
  endpoint_list_route: "listroute"
  endpoint_episode_log: "eplog"
  endpoint_simulation_time: "time"
  endpoint_simulation_info: "siminfo"
  endpoint_upload_sector: "sector"

  endpoint_shutdown: "shutdown"
  endpoint_metrics: "metric"
  query_aircraft_id: "callsign"

  # Column/element/attribute names
  aircraft_type: "aircraft_type"
  cleared_flight_level: "cleared_flight_level"
  current_flight_level: "current_flight_level"
  requested_flight_level: "requested_flight_level"
  latitude: "latitude"
  longitude: "longitude"
  altitude: "altitude"
  ground_speed: "ground_speed"
  heading: "heading"
  vertical_speed: "vertical_speed"
  simulator_time: "scenario_time"

  # Metrics
  loss_of_separation: "pairwise_separation_metric"
  sector_exit: "sector_exit_metric"
  fuel_efficiency: "fuel_efficiency_metric"

  # Physical
  feet_altitude_upper_limit: 6000
  flight_level_lower_limit: 60
  flight_level_upper_limit: 450
